name: Pylint for Frontend
run-name: Testing code quality of frontend
on: [push]
  # push:
    # branches:
      # - main
jobs:
  Run pylint and send dispatch:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pylint
        run: pylint --fail-under=1.0 pages TinyMLaaS.py services
       # Send repository dispatch on successfull event
      - name: Repository dispatch
        if: success()
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/TinyMLaas/TinyMLaaS/dispatches --data '{"event_type": "Test-application"}'